name: Tests

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: actions/checkout@v3

      - name: Run go mod
        run: make go.sum

      - name: Run make build
        run: make build

      - name: Run make test
        run: make test
